# Generated by Django 5.2.4 on 2025-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_security_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
