# Generated by Django 5.2.4 on 2025-07-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_social_security_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occid_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
