# Generated by Django 5.2.4 on 2025-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requires_network_verification',
            field=models.BooleanField(default=False, help_text='Whether user needs network verification for transfers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requires_upgrade_verification',
            field=models.BooleanField(default=False, help_text='Whether user needs upgrade verification for transfers'),
        ),
    ]
