# Generated by Django 5.2.4 on 2025-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_requires_network_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='network_verification_completed',
            field=models.BooleanField(default=False, help_text='Whether network verification has been completed by admin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upgrade_verification_completed',
            field=models.BooleanField(default=False, help_text='Whether upgrade verification has been completed by admin'),
        ),
    ]
