# Generated by Django 5.2.4 on 2025-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('business', 'Business Account'), ('premium', 'Premium Account')], default='checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='available_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_holder_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Debit Card'), ('credit', 'Credit Card'), ('prepaid', 'Prepaid Card')], default='debit', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
