# Generated by Django 5.2.4 on 2025-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deposit_transaction_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer_internal', 'BetaBank Transfer'), ('transfer_external', 'External Bank Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('fee', 'Service Fee'), ('investment', 'Investment'), ('investment_withdrawal', 'Investment Withdrawal')], max_length=25),
        ),
    ]
