# Generated by Django 5.2.4 on 2025-07-29 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(default='Customer Service', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_deposits', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_reply_chats', models.BooleanField(default=True)),
                ('can_verify_accounts', models.BooleanField(default=True)),
                ('can_manage_transactions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Manager',
                'verbose_name_plural': 'Bank Managers',
            },
        ),
        migrations.CreateModel(
            name='ManagerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_balance_updated', 'User Balance Updated'), ('deposit_verified', 'Deposit Verified'), ('deposit_rejected', 'Deposit Rejected'), ('chat_replied', 'Chat Reply Sent'), ('account_verified', 'Account Verified'), ('transaction_reviewed', 'Transaction Reviewed'), ('user_profile_updated', 'User Profile Updated')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='manager.bankmanager')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Activity',
                'verbose_name_plural': 'Manager Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManagerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='manager.bankmanager')),
            ],
            options={
                'verbose_name': 'Manager Session',
                'verbose_name_plural': 'Manager Sessions',
                'ordering': ['-login_time'],
            },
        ),
    ]
