# Generated by Django 5.2.4 on 2025-09-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageractivity',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managersession',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='manageractivity',
            name='target_user',
        ),
        migrations.DeleteModel(
            name='BankManager',
        ),
        migrations.DeleteModel(
            name='ManagerSession',
        ),
        migrations.DeleteModel(
            name='ManagerActivity',
        ),
    ]
